In [5]:
import pandas as pd

In [7]:
df = pd.read_excel("smart_sales_dataset.xlsx")

In [9]:
df

,Date,Product,Category,Quantity,Selling Price,Cost Price,Customer
0,15-01-2026,Cap,Clothing,NaN,389.0,85.0,C016
1,18-01-2026,Shoes,Footwear,1.0,1573.0,944.0,C035
2,17-03-2026,T-Shirt,Clothing,4.0,408.0,253.0,C006
3,30-01-2026,Shoes,Footwear,5.0,1554.0,853.0,C036
4,02-04-2026,Shoes,Footwear,5.0,1507.0,878.0,C029
...,...,...,...,...,...,...,...
180,17-04-2026,T-Shirt,Clothing,3.0,549.0,671.0,C010
181,21-04-2026,Shoes,Footwear,2.0,1445.0,902.0,C002
182,16-03-2026,T-Shirt,Clothing,4.0,528.0,317.0,C011
183,12-03-2026,Bag,Accessories,1.0,877.0,386.0,C014
184,17-04-2026,Watch,Accessories,1.0,1220.0,652.0,C048

In [11]:
df.describe

<bound method NDFrame.describe of            Date  Product     Category  Quantity  Selling Price  Cost Price  \
0    15-01-2026      Cap     Clothing       NaN          389.0        85.0
1    18-01-2026    Shoes     Footwear       1.0         1573.0       944.0
2    17-03-2026  T-Shirt     Clothing       4.0          408.0       253.0
3    30-01-2026    Shoes     Footwear       5.0         1554.0       853.0
4    02-04-2026    Shoes     Footwear       5.0         1507.0       878.0
..          ...      ...          ...       ...            ...         ...
180  17-04-2026  T-Shirt     Clothing       3.0          549.0       671.0
181  21-04-2026    Shoes     Footwear       2.0         1445.0       902.0
182  16-03-2026  T-Shirt     Clothing       4.0          528.0       317.0
183  12-03-2026      Bag  Accessories       1.0          877.0       386.0
184  17-04-2026    Watch  Accessories       1.0         1220.0       652.0

    Customer
0       C016
1       C035
2       C006
3       C036
4       C029
..       ...
180     C010
181     C002
182     C011
183     C014
184     C048

[185 rows x 7 columns]>

In [13]:
df = df.drop_duplicates()

In [15]:
df.describe

<bound method NDFrame.describe of            Date  Product     Category  Quantity  Selling Price  Cost Price  \
0    15-01-2026      Cap     Clothing       NaN          389.0        85.0
1    18-01-2026    Shoes     Footwear       1.0         1573.0       944.0
2    17-03-2026  T-Shirt     Clothing       4.0          408.0       253.0
3    30-01-2026    Shoes     Footwear       5.0         1554.0       853.0
4    02-04-2026    Shoes     Footwear       5.0         1507.0       878.0
..          ...      ...          ...       ...            ...         ...
176  13-03-2026  T-Shirt     Clothing       4.0          555.0       326.0
177  10-04-2026    Shoes     Footwear       5.0         1497.0       907.0
178  21-04-2026    Watch  Accessories       5.0         1209.0       689.0
179  08-01-2026   Hoodie     Clothing       5.0         1289.0      1455.0
180  17-04-2026  T-Shirt     Clothing       3.0          549.0       671.0

    Customer
0       C016
1       C035
2       C006
3       C036
4       C029
..       ...
176     C040
177     C029
178     C037
179     C049
180     C010

[181 rows x 7 columns]>

In [17]:
df = df.dropna()

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 173 entries, 1 to 180
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           173 non-null    object
 1   Product        173 non-null    object
 2   Category       173 non-null    object
 3   Quantity       173 non-null    float64
 4   Selling Price  173 non-null    float64
 5   Cost Price     173 non-null    float64
 6   Customer       173 non-null    object
dtypes: float64(3), object(4)
memory usage: 10.8+ KB

In [21]:
df.describe

<bound method NDFrame.describe of            Date  Product     Category  Quantity  Selling Price  Cost Price  \
1    18-01-2026    Shoes     Footwear       1.0         1573.0       944.0
2    17-03-2026  T-Shirt     Clothing       4.0          408.0       253.0
3    30-01-2026    Shoes     Footwear       5.0         1554.0       853.0
4    02-04-2026    Shoes     Footwear       5.0         1507.0       878.0
5    05-02-2026   Hoodie     Clothing       1.0         1294.0       570.0
..          ...      ...          ...       ...            ...         ...
176  13-03-2026  T-Shirt     Clothing       4.0          555.0       326.0
177  10-04-2026    Shoes     Footwear       5.0         1497.0       907.0
178  21-04-2026    Watch  Accessories       5.0         1209.0       689.0
179  08-01-2026   Hoodie     Clothing       5.0         1289.0      1455.0
180  17-04-2026  T-Shirt     Clothing       3.0          549.0       671.0

    Customer
1       C035
2       C006
3       C036
4       C029
5       C045
..       ...
176     C040
177     C029
178     C037
179     C049
180     C010

[173 rows x 7 columns]>

In [23]:
df["Profit"] = (df["Selling Price"] - df["Cost Price"]) * df["Quantity"]

C:\Users\JANARDHAN_R\AppData\Local\Temp\ipykernel_36308\1600736305.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Profit"] = (df["Selling Price"] - df["Cost Price"]) * df["Quantity"]

In [25]:
df.columns

Index(['Date', 'Product', 'Category', 'Quantity', 'Selling Price',
       'Cost Price', 'Customer', 'Profit'],
      dtype='object')

In [27]:
df = df.copy()
df["Profit"] = (df["Selling Price"] - df["Cost Price"]) * df["Quantity"]

In [29]:
df.loc[:, "Profit"] = (df["Selling Price"] - df["Cost Price"]) * df["Quantity"]

In [31]:
df.describe

<bound method NDFrame.describe of            Date  Product     Category  Quantity  Selling Price  Cost Price  \
1    18-01-2026    Shoes     Footwear       1.0         1573.0       944.0
2    17-03-2026  T-Shirt     Clothing       4.0          408.0       253.0
3    30-01-2026    Shoes     Footwear       5.0         1554.0       853.0
4    02-04-2026    Shoes     Footwear       5.0         1507.0       878.0
5    05-02-2026   Hoodie     Clothing       1.0         1294.0       570.0
..          ...      ...          ...       ...            ...         ...
176  13-03-2026  T-Shirt     Clothing       4.0          555.0       326.0
177  10-04-2026    Shoes     Footwear       5.0         1497.0       907.0
178  21-04-2026    Watch  Accessories       5.0         1209.0       689.0
179  08-01-2026   Hoodie     Clothing       5.0         1289.0      1455.0
180  17-04-2026  T-Shirt     Clothing       3.0          549.0       671.0

    Customer  Profit
1       C035   629.0
2       C006   620.0
3       C036  3505.0
4       C029  3145.0
5       C045   724.0
..       ...     ...
176     C040   916.0
177     C029  2950.0
178     C037  2600.0
179     C049  -830.0
180     C010  -366.0

[173 rows x 8 columns]>

In [33]:
df["Profit"] = (df["Selling Price"] - df["Cost Price"]) * df["Quantity"]
df["Revenue"] = df["Selling Price"] * df["Quantity"]

In [35]:
df["Profit"]

1       629.0
2       620.0
3      3505.0
4      3145.0
5       724.0
        ...
176     916.0
177    2950.0
178    2600.0
179    -830.0
180    -366.0
Name: Profit, Length: 173, dtype: float64

In [37]:
df.describe

<bound method NDFrame.describe of            Date  Product     Category  Quantity  Selling Price  Cost Price  \
1    18-01-2026    Shoes     Footwear       1.0         1573.0       944.0
2    17-03-2026  T-Shirt     Clothing       4.0          408.0       253.0
3    30-01-2026    Shoes     Footwear       5.0         1554.0       853.0
4    02-04-2026    Shoes     Footwear       5.0         1507.0       878.0
5    05-02-2026   Hoodie     Clothing       1.0         1294.0       570.0
..          ...      ...          ...       ...            ...         ...
176  13-03-2026  T-Shirt     Clothing       4.0          555.0       326.0
177  10-04-2026    Shoes     Footwear       5.0         1497.0       907.0
178  21-04-2026    Watch  Accessories       5.0         1209.0       689.0
179  08-01-2026   Hoodie     Clothing       5.0         1289.0      1455.0
180  17-04-2026  T-Shirt     Clothing       3.0          549.0       671.0

    Customer  Profit  Revenue
1       C035   629.0   1573.0
2       C006   620.0   1632.0
3       C036  3505.0   7770.0
4       C029  3145.0   7535.0
5       C045   724.0   1294.0
..       ...     ...      ...
176     C040   916.0   2220.0
177     C029  2950.0   7485.0
178     C037  2600.0   6045.0
179     C049  -830.0   6445.0
180     C010  -366.0   1647.0

[173 rows x 9 columns]>

In [39]:
df.head(5)

,Date,Product,Category,Quantity,Selling Price,Cost Price,Customer,Profit,Revenue
1,18-01-2026,Shoes,Footwear,1.0,1573.0,944.0,C035,629.0,1573.0
2,17-03-2026,T-Shirt,Clothing,4.0,408.0,253.0,C006,620.0,1632.0
3,30-01-2026,Shoes,Footwear,5.0,1554.0,853.0,C036,3505.0,7770.0
4,02-04-2026,Shoes,Footwear,5.0,1507.0,878.0,C029,3145.0,7535.0
5,05-02-2026,Hoodie,Clothing,1.0,1294.0,570.0,C045,724.0,1294.0

In [41]:
df.isnull().sum()

Date             0
Product          0
Category         0
Quantity         0
Selling Price    0
Cost Price       0
Customer         0
Profit           0
Revenue          0
dtype: int64

In [43]:
df.to_excel("cleaned_sales_data.xlsx", index=False)